### ISSUE TITLE
[Test] Không rõ cách submit bài làm

### ISSUE THREAD

**Issue by manhdung20112000** [Foundation-Learning-UETAILab/Week-0-Introduction#2]
## ❓ Question

Em thử submit bằng Pull request nhưng không thấy có hiện tượng gì. Làm thế nào bây giờ ạ?

**Comment by HaiNguyen2903** [comment]
oke e, like và theo dõi repo để update cách sử dụng và nộp bài nhé

**Comment by manhdung20112000** [comment]
Dạ vâng ạ
